AWSTemplateFormatVersion: "2010-09-09"
Description: My first lambda function 
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  My_FirstLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Hello_Function
      Role: !GetAtt Hello_Function.Arn
      Runtime: python3.7
      Handler: index.my_handler
      Code:
        ZipFile: |
          def my_handler(event, context):
            message = 'Hello Lambda World!'
                return message

   S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: "first_s3bucket"
      VersioningConfiguration:
        Status: Enabled
  Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket


