- name: deploy my_lambda_function
  hosts: 127.0.0.1
  connection: local
  Users: Admin
  tasks:
  - name: Creating lambda_role
    iam_role:
      name: "lambda_role"
      assume_role_policy_document: ""
      state: present
    register: lambda_role
      - name: Assign IAM policy to role
    iam_policy:
      iam_type: role
      iam_name: "lambda_role"
      policy_name: "lambda_iam_role_policy"
      state: present
      policy_json: ""
       - name: Creating ZIP file for code.py
    shell: "zip -j /..path/code.py.zip ./..path/code.py"
  - name: Creating Lambda Function
    lambda:
      region: "us-west-2"
      state: present
      description: "Running the function"
      name: "Hello_Ebere"
      zip_file: "/...path/code.py.zip"
      runtime: python3.7
      role: ""
      handler: "Hello_Ebere.main"
      timeout: 360
    register: lambda_function









    